parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"fcMS":[function(require,module,exports) {
function o(o,e){if(!(o instanceof e))throw new TypeError("Cannot call a class as a function")}module.exports=o,module.exports.default=module.exports,module.exports.__esModule=!0;
},{}],"P8NW":[function(require,module,exports) {
function e(e,o){for(var r=0;r<o.length;r++){var t=o[r];t.enumerable=t.enumerable||!1,t.configurable=!0,"value"in t&&(t.writable=!0),Object.defineProperty(e,t.key,t)}}function o(o,r,t){return r&&e(o.prototype,r),t&&e(o,t),o}module.exports=o,module.exports.default=module.exports,module.exports.__esModule=!0;
},{}],"E7HD":[function(require,module,exports) {
function e(e){if(void 0===e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return e}module.exports=e,module.exports.default=module.exports,module.exports.__esModule=!0;
},{}],"AkAO":[function(require,module,exports) {
function e(o,t){return module.exports=e=Object.setPrototypeOf||function(e,o){return e.__proto__=o,e},module.exports.default=module.exports,module.exports.__esModule=!0,e(o,t)}module.exports=e,module.exports.default=module.exports,module.exports.__esModule=!0;
},{}],"d4H2":[function(require,module,exports) {
var e=require("./setPrototypeOf.js");function o(o,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function");o.prototype=Object.create(t&&t.prototype,{constructor:{value:o,writable:!0,configurable:!0}}),t&&e(o,t)}module.exports=o,module.exports.default=module.exports,module.exports.__esModule=!0;
},{"./setPrototypeOf.js":"AkAO"}],"b9XL":[function(require,module,exports) {
function o(e){return"function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?(module.exports=o=function(o){return typeof o},module.exports.default=module.exports,module.exports.__esModule=!0):(module.exports=o=function(o){return o&&"function"==typeof Symbol&&o.constructor===Symbol&&o!==Symbol.prototype?"symbol":typeof o},module.exports.default=module.exports,module.exports.__esModule=!0),o(e)}module.exports=o,module.exports.default=module.exports,module.exports.__esModule=!0;
},{}],"pxk2":[function(require,module,exports) {
var e=require("@babel/runtime/helpers/typeof").default,t=require("./assertThisInitialized.js");function o(o,r){return!r||"object"!==e(r)&&"function"!=typeof r?t(o):r}module.exports=o,module.exports.default=module.exports,module.exports.__esModule=!0;
},{"@babel/runtime/helpers/typeof":"b9XL","./assertThisInitialized.js":"E7HD"}],"UJE0":[function(require,module,exports) {
function e(o){return module.exports=e=Object.setPrototypeOf?Object.getPrototypeOf:function(e){return e.__proto__||Object.getPrototypeOf(e)},module.exports.default=module.exports,module.exports.__esModule=!0,e(o)}module.exports=e,module.exports.default=module.exports,module.exports.__esModule=!0;
},{}],"jwEd":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("@babel/runtime/helpers/classCallCheck")),t=a(require("@babel/runtime/helpers/createClass")),r=a(require("@babel/runtime/helpers/assertThisInitialized")),s=a(require("@babel/runtime/helpers/inherits")),o=a(require("@babel/runtime/helpers/possibleConstructorReturn")),n=a(require("@babel/runtime/helpers/getPrototypeOf"));function a(e){return e&&e.__esModule?e:{default:e}}function u(e){var t=i();return function(){var r,s=(0,n.default)(e);if(t){var a=(0,n.default)(this).constructor;r=Reflect.construct(s,arguments,a)}else r=s.apply(this,arguments);return(0,o.default)(this,r)}}function i(){if("undefined"==typeof Reflect||!Reflect.construct)return!1;if(Reflect.construct.sham)return!1;if("function"==typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(e){return!1}}var l=wp.element,c=l.Component,p=l.Fragment,h=l.createElement,m=wp.components.Popover,f=wp,d=f.apiFetch,v=wp.i18n.__,b=function(o){(0,s.default)(a,o);var n=u(a);function a(){var t;return(0,e.default)(this,a),(t=n.apply(this,arguments)).state={search:"",dossiers:[],error:""},t.searchDossierName=t.searchDossierName.bind((0,r.default)(t)),t.selectDossierName=t.selectDossierName.bind((0,r.default)(t)),t}return(0,t.default)(a,[{key:"searchDossierName",value:function(e){var t=this,r=this.state.search;this.setState({search:e}),e.length<r.length&&this.setState({dossiers:[]});var s="/wp/v2/dossiers?parent=0";e&&(s+="&search="+encodeURIComponent(e)),d({path:s}).then(function(e){t.setState({dossiers:e})},function(e){t.setState({error:e.message})})}},{key:"selectDossierName",value:function(e,t){var r=this.props.onSelectDossier;return e.preventDefault(),this.setState({search:"",dossiers:[],error:""}),r({dossierID:t})}},{key:"render",value:function(){var e,t=this,r=this.state,s=r.search,o=r.dossiers,n=v("Nom de la DocuThèque","docutheques"),a=v("Entrer le nom de la DocuThèque ici…","docutheques");return o.length&&(e=o.map(function(e){return h("button",{type:"button",key:"editor-autocompleters__item-item-"+e.id,role:"option","aria-selected":"true",className:"components-button components-autocomplete__result editor-autocompleters__user",onClick:function(r){return t.selectDossierName(r,e.id)}},h("span",{key:"name",className:"editor-autocompleters__user-name"},e.name))})),h(p,null,h("input",{type:"text",value:s,className:"components-placeholder__input","aria-label":n,placeholder:a,onChange:function(e){return t.searchDossierName(e.target.value)}}),0!==o.length&&h(m,{className:"components-autocomplete__popover",focusOnMount:!1,position:"bottom left"},h("div",{className:"components-autocomplete__results"},e)))}}]),a}(c),_=b;exports.default=_;
},{"@babel/runtime/helpers/classCallCheck":"fcMS","@babel/runtime/helpers/createClass":"P8NW","@babel/runtime/helpers/assertThisInitialized":"E7HD","@babel/runtime/helpers/inherits":"d4H2","@babel/runtime/helpers/possibleConstructorReturn":"pxk2","@babel/runtime/helpers/getPrototypeOf":"UJE0"}],"sPO8":[function(require,module,exports) {
"use strict";var e=t(require("./components/autocompleter"));function t(e){return e&&e.__esModule?e:{default:e}}var o=wp.blocks.registerBlockType,u=wp.element,s=u.createElement,l=u.Fragment,r=wp.components,n=r.Placeholder,i=r.Disabled,a=r.Toolbar,c=r.ToolbarButton,d=r.PanelBody,p=r.SelectControl,m=wp.blockEditor,h=m.BlockControls,b=m.InspectorControls,q=wp.editor.ServerSideRender,D=wp.i18n.__,f=function(t){var o=t.attributes,u=t.setAttributes,r=o.orderDocumentsBy,m=o.orderDossiersBy;return o.dossierID?s(l,null,s(h,null,s(a,null,s(c,{icon:"edit",title:D("Choisir une autre DocuThèque","docutheques"),onClick:function(){u({dossierID:0})}}))),s(b,null,s(d,{title:D("Réglages","docutheques"),initialOpen:!0},s(p,{label:D("Classer les dossiers :","docutheques"),value:m,onChange:function(e){u({orderDossiersBy:e})},options:[{label:D("Alphabétiquement (A - Z)","docutheques"),value:"name"},{label:D("Les plus récents en premier (31 - 1)","docutheques"),value:"newer"},{label:D("Les moins récents en premier (1 - 31)","docutheques"),value:"older"}]}),s(p,{label:D("Classer les documents selon leur :","docutheques"),value:r,onChange:function(e){u({orderDocumentsBy:e})},options:[{label:D("Date de publication (31 - 1)","docutheques"),value:"date"},{label:D("Date de modification (31 - 1)","docutheques"),value:"modified"},{label:D("Nom (A - Z)","docutheques"),value:"title"}]}))),s(i,null,s(q,{block:"docutheques/browser",attributes:o}))):s(n,{icon:"portfolio",label:D("DocuThèques","docutheques"),instructions:D("Commencer à saisir le nom de la DocuThèque que vous souhaitez intégrer dans cette publication.","docutheques")},s(e.default,{onSelectDossier:u}))};o("docutheques/browser",{supports:{className:!1,anchor:!1,multiple:!1,reusable:!1},title:D("DocuThèques","docutheques"),description:D("Explorateur de documents.","docutheques"),icon:"portfolio",category:"widgets",attributes:{dossierID:{type:"integer",default:0},orderDocumentsBy:{type:"string",default:"date",enum:["date","modified","title"]},orderDossiersBy:{type:"string",default:"name",enum:["newer","older","name"]}},edit:f});
},{"./components/autocompleter":"jwEd"}]},{},["sPO8"], null)
//# sourceMappingURL=/block/index.js.map